# Generated by Django 5.1.1 on 2024-09-05 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0002_alter_location_options_alter_rack_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rack',
            name='room',
        ),
    ]
