# Generated by Django 5.1.1 on 2024-09-06 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0003_remove_rack_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rack',
            old_name='total_shelf',
            new_name='total_shelves',
        ),
        migrations.AddField(
            model_name='rack',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='inventory_app.room'),
            preserve_default=False,
        ),
    ]
