# Generated by Django 5.1.1 on 2024-09-09 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0004_rename_total_shelf_rack_total_shelves_rack_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produkt', 'verbose_name_plural': 'Produkty'},
        ),
        migrations.RemoveField(
            model_name='location',
            name='room',
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=100, verbose_name='Značka'),
        ),
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.ManyToManyField(blank=True, null=True, to='inventory_app.location', verbose_name='Umístění'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Název'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Kód'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='number',
            field=models.IntegerField(verbose_name='Číslo'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='inventory_app.room', verbose_name='Místnost'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='total_shelves',
            field=models.IntegerField(verbose_name='Celkový počet polic'),
        ),
    ]
