# Generated by Django 5.1.1 on 2024-09-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0006_product_slug_alter_location_shelf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Kód'),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
