# Generated by Django 5.1.1 on 2024-09-17 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0008_alter_product_name_alter_product_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Úkol', 'verbose_name_plural': 'Úkoly'},
        ),
        migrations.AddField(
            model_name='product',
            name='old_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default=1, verbose_name='Popis'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='task',
            field=models.CharField(default=1, max_length=150, verbose_name='Úkol'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='rack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='inventory_app.rack', verbose_name='Regál'),
        ),
    ]
